### ISSUE TITLE
Hi I'm new to the site and don't know how to msg

### ISSUE THREAD

**Issue by pahtr1ck** [boooooooaq/Tokyo-Night-Konsole#1]
https://github.com/mwittrien/BetterDiscordAddons/issues/2502#issue-1950847417

Did you ever get a solution to this? I'm having this problem now a year later.

**Comment by boooooooaq** [comment]
You just have to wait for the dev's to update BDFDB, if you still have this issue a few days from now, try to reinstall the plugin from the website and if that still doesn't fix it, open a bug report like I did a year ago.
